const pieces={
identity:{kicker:'ABOUT ME',title:'祝潇灵的 AI 作品展',body:`<p class="lead">这是我四周里留下来的东西：一些完成的作品，一些做错后重新想过的事情，以及一套还在慢慢形成的做事方式。</p><p>工商管理专业｜北辰青年线上实习生</p><p>温柔、认真、高敏感、高标准。它们不是一张介绍里的标签，而是我在做事时会反复遇见的自己。</p>`},
manual:{kicker:'WEEK 01 · PERSONAL MANUAL',title:'第一次遇见 AI，我先拿它来认识自己',body:`<p>第一周，我第一次接触 AI Agent。我用对话的方式完成了一份《AI 时代个人说明书》，里面写了我的沟通方式、做事习惯、压力状态和团队协作方式。</p><p>刚开始的时候，我其实不太会用。网站改了很多遍，才慢慢变成我想要的样子。那时我学会的，不只是怎么生成页面，也是怎么把自己的想法说清楚。</p><p>这是我第一次感觉到，AI 不只是用来聊天的。只要我愿意把需求说清楚，它可以陪我把一件事从想法做到能展示出来。</p>`,actions:`<a href="https://c7be034877a74520af64aeab7ddf78b0.app.workbuddy.link" target="_blank" rel="noreferrer">打开个人说明书网站 ↗</a>`},
team:{kicker:'WEEK 01 · TEAM',title:'第一次当小组长，我们先玩了一场剧本杀',body:`<p>第一周，我主动担任了小组长，开始协调大家的分工。我们设置了共创官、氛围官、技术官等角色，让每个人都有自己可以负责的事情。</p><p>为了让大家更快认识彼此，我们组织了一次剧本杀形式的共创会。大家觉得很新奇，现场氛围也很好。</p><p>但路演时，我们发现内容没有完全讲清楚。导师后来提醒我们，可以用 FAB 去想：这个内容有什么特点，能带来什么好处，最终要让别人记住什么。</p><p class="lead">这次之后，我开始习惯在做一件事之前先问自己：我到底想解决什么问题？</p>`,actions:`<a href="https://25e045ac42eb4d65ba279d2e64cb7c20.app.workbuddy.link" target="_blank" rel="noreferrer">打开小组网站 ↗</a>`},
research:{kicker:'WEEK 02 · USER RESEARCH',title:'我原本以为，大一最需要的是更多活动',body:`<p>第二周，我们开始为北辰青年招募校园行动合伙人。我的小小组负责大一新生，调研方式包括访谈、问卷和公开信息收集。</p><p>整理资料时，我发现自己最开始的想法并不完整。我原本以为，大一新生最需要的是更多活动机会；但从问卷结果、访谈共性和资料整理出的规律来看，他们更需要的是明确的引导：</p><p class="lead">可以参加什么、自己要做什么、参与后能得到什么，以及下一步怎样开始。</p><p>最后，全组综合四个年级的调研结果，选择了现大二学生作为优先招募人群。</p>`},
xiaohongshu:{kicker:'WEEK 02 · CONTENT',title:'内容做得很多，不一定会留下重点',body:`<p>在校园行动合伙人招募中，我负责小红书图文的排版和设计。</p><p>我一开始更关注画面是否完整、内容是否丰富。路演时，导师问我们：“你们真正想让别人记住什么？”</p><p>这个问题让我重新看了一遍自己的物料。我发现，原来的内容可能有两个问题：重点不够突出，设计风格也不够统一。</p><p class="lead">做内容不是把所有信息都放进去，而是先决定最重要的一句话，再让其他内容为它服务。</p>`},
website:{kicker:'WEEK 02 · INTERACTIVE WEBSITE',title:'把一次招募，做成一次可以亲自体验的行动',body:`<p>为了让大家更直观地理解校园行动合伙人，我设计了一个沉浸式交互网站。</p><p>我自己确定了游戏化体验、七屏路径和五关任务：找到队友、设计方案、招募参与者、现场应变和项目复盘。</p><div class="split"><div><strong>我决定的</strong>游戏化体验<br>七屏路径<br>五关任务</div><div><strong>AI 协助的</strong>网页代码<br>文案生成<br>页面实现</div></div><p>导师认为这个网站有点像产品，也建议我把具体行动路径做得更清楚。</p>`,actions:`<a href="https://5380e337c7d6444fbe9a8e0dda3d8986.app.workbuddy.link" target="_blank" rel="noreferrer">体验行动合伙人网站 ↗</a>`},
interview:{kicker:'WEEK 03 · INTERVIEW',title:'第一印象来得很快，但不能停在那里',body:`<p>第三周，我们分成四个小组，面试四位校园行动合伙人应聘者。我们作为面试官，使用五个问题完成面试，并制作 PPT 汇报观察和复盘。</p><p>这次经历让我发现，履历、头衔、表达和气场都会很快影响判断，但它们不能直接证明一个人真正做过什么。</p><p>更可靠的判断，需要继续追问：</p><ul><li>这件事里，你本人具体做了什么？</li><li>最后产生了什么结果？</li><li>当时为什么这样判断？</li><li>如果重新来一次，你会怎么调整？</li></ul>`},
skill:{kicker:'MY SKILL · JOB SEARCH',title:'旧简历已经装不下新的经历，所以我做了一个会追问的 Skill',body:`<p>这个 Skill 是我从零设计的。一方面，这是课程任务的一部分；另一方面，我也确实需要它帮助自己找工作。</p><p>原来的简历已经比较旧，所以我最先确定的功能，是让它先向我提问最近新增的实习和项目经历。</p><p>我第一次用它测试字节跳动 AI 产品经理—数据平台岗位。它帮助我分析 JD、匹配个人经历、改写简历，并生成 HTML/PDF 版本。</p><p class="lead">简历不能只写“参与过什么”，还要写清楚“我本人做了什么、最后产生了什么结果”。</p>`},
reflection:{kicker:'DESK NOTE · REFLECTION',title:'做完一件事，不要急着翻篇',body:`<p class="lead">我希望以后能坚持用 KISS 法则做复盘。</p><p>不用写很长，每次任务结束后，简单留下几句话：</p><ul><li>我原本想做什么？</li><li>我实际做了什么？</li><li>哪个地方没有做好？</li><li>下次可以怎么改？</li></ul><p>我想让复盘变成一种习惯，而不是只有遇到问题时才想起来。</p>`},
computer:{kicker:'OPEN MY WEBSITES',title:'还有两个网站，想邀请你亲自看看',body:`<p>一个是我第一次做的个人说明书网站，另一个是我把校园行动合伙人招募做成体验路径的网站。</p><p>它们都不是一开始就做好的，里面有我反复修改的痕迹，也有 AI 帮忙实现的部分。</p>`,actions:`<a href="https://c7be034877a74520af64aeab7ddf78b0.app.workbuddy.link" target="_blank" rel="noreferrer">个人说明书 ↗</a><a class="secondary" href="https://5380e337c7d6444fbe9a8e0dda3d8986.app.workbuddy.link" target="_blank" rel="noreferrer">行动合伙人体验 ↗</a>`},
contact:{kicker:'CONTACT',title:'如果你还想了解我，可以给我留个消息',body:`<p class="lead">祝潇灵</p><p>工商管理专业<br>北辰青年线上实习生</p><p>如果你想继续了解我的作品、经历，或者只是想打个招呼，都欢迎联系我。</p>`,actions:`<a href="mailto:请填写你的邮箱">给我发邮件 ↗</a><button class="secondary copy-wechat" type="button">复制微信号</button>`},
fish:{kicker:'A LITTLE EASTER EGG',title:'今天也有在往前游。',body:`<p class="lead">这条小鱼没有什么大道理。</p><p>它只是提醒我，事情可以慢慢做，路也可以一步一步走。</p>`}
};
const scene=document.querySelector('#scene'),modal=document.querySelector('#modal'),paper=document.querySelector('.modal-paper'),mark=document.querySelector('#modalMark'),title=document.querySelector('#modalTitle'),kicker=document.querySelector('#modalKicker'),body=document.querySelector('#modalBody'),actions=document.querySelector('#modalActions'),closeBtn=document.querySelector('#closeBtn'),toast=document.querySelector('#toast');let lastFocused=null;
const exhibitCodes={identity:'00',manual:'01',team:'02',research:'03',xiaohongshu:'04',website:'05',interview:'06',skill:'07',reflection:'08',contact:'09',fish:'10'};
function openPiece(key,trigger){const p=pieces[key];if(!p)return;lastFocused=document.activeElement;const rect=trigger.getBoundingClientRect();const dx=Math.round(rect.left+rect.width/2-window.innerWidth/2),dy=Math.round(rect.top+rect.height/2-window.innerHeight/2);paper.style.setProperty('--fly-x',`${dx}px`);paper.style.setProperty('--fly-y',`${dy}px`);paper.style.setProperty('--fly-r',`${dx>0?'8deg':'-8deg'}`);document.querySelectorAll('.hotspot').forEach(el=>el.classList.toggle('selected',el===trigger));kicker.textContent=p.kicker;title.textContent=p.title;body.innerHTML=p.body;actions.innerHTML=p.actions||'';mark.textContent=exhibitCodes[key]||'00';modal.dataset.piece=key;modal.classList.remove('open');void modal.offsetWidth;window.setTimeout(()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';closeBtn.focus()},190);const copy=actions.querySelector('.copy-wechat');if(copy)copy.addEventListener('click',()=>showToast('微信号等你填写后，我再帮你接上。'))}
function closeModal(){modal.classList.remove('open');document.querySelectorAll('.hotspot').forEach(el=>el.classList.remove('selected'));modal.setAttribute('aria-hidden','true');document.body.style.overflow='';lastFocused?.focus()}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2600)}
document.querySelectorAll('.hotspot').forEach(el=>{el.addEventListener('click',()=>{if(el.dataset.piece==='fish')showToast('今天也有在往前游。');openPiece(el.dataset.piece,el)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}})});closeBtn.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});
